import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: 'http',
        hostname: '**',
      },
      {
        protocol: 'https',
        hostname: '**',
      },
    ],
  },
  async redirects() {
    return [
      {
        source: '/doctor',
        destination: '/doctors',
        permanent: true,
      },
      {
        source: '/treatments/piles',
        destination: '/doctor/near-me/treat/general-surgery/laser-piles-treatment',
        permanent: true,
      },
      {
        source: '/treatments/fistula',
        destination: '/doctor/near-me/treat/general-surgery/fistula-laser-treatment',
        permanent: true,
      },
      {
        source: '/treatments/fissure',
        destination: '/doctor/near-me/treat/general-surgery/anal-fissure-treatment',
        permanent: true,
      },
      {
        source: '/treatments/gallbladder',
        destination: '/doctor/near-me/treat/general-surgery/laparoscopic-gallbladder-removal',
        permanent: true,
      },
      {
        source: '/treatments/appendix',
        destination: '/doctor/near-me/treat/general-surgery/laparoscopic-appendix-surgery',
        permanent: true,
      },
      {
        source: '/treatments/hernia',
        destination: '/doctor/near-me/treat/general-surgery/laparoscopic-hernia-repair',
        permanent: true,
      },
      {
        source: '/treatments/hysterectomy',
        destination: '/doctor/near-me/treat/obstetrics-gynaecology/laparoscopic-hysterectomy-guide',
        permanent: true,
      },
      {
        source: '/insurance',
        destination: '/patients/insurance',
        permanent: true,
      },
      {
        source: '/for-doctors',
        destination: '/professionals',
        permanent: true,
      },
      {
        source: '/appointment-booking',
        destination: '/book-appointment',
        permanent: true,
      },
      // --- START AUDIT RECOVERY REDIRECTS ---
      { source: '/blog/:id', destination: '/blog', permanent: true },
      { source: '/doctor/near-me/treat/general-surgery/gallbladder-removal-recovery', destination: '/doctor/near-me/treat/general-surgery/laparoscopic-gallbladder-removal', permanent: true },
      { source: '/doctor/near-me/treat/emergency-services', destination: '/doctor/near-me/treat/emergency-medicine', permanent: true },
      { source: '/doctor/near-me/treat/icu-facility', destination: '/doctor/near-me/treat/critical-care-emergency-medicine', permanent: true },
      { source: '/doctor/near-me/treat/laser-piles-surgery', destination: '/doctor/near-me/treat/proctology/laser-piles-treatment', permanent: true },
      { source: '/doctor/near-me/treat/obstetrics-gynecology-infertility', destination: '/doctor/near-me/treat/obstetrics-gynaecology/maternity', permanent: true },
      { source: '/doctor/near-me/treat/joint-replacement-surgery', destination: '/doctor/near-me/treat/orthopaedics/knee-replacement', permanent: true },
      { source: '/doctor/near-me/treat/nephrology-dialysis', destination: '/doctor/near-me/treat/nephrology/dialysis', permanent: true },
      { source: '/doctor/near-me/treat/gastro-enterology', destination: '/doctor/near-me/treat/gastroenterology/liver-transplant', permanent: true },
      { source: '/doctor/near-me/treat/surgical-gastro-enterology', destination: '/doctor/near-me/treat/gastroenterology/ercp-bile-duct-stone-removal', permanent: true },
      { source: '/doctor/near-me/treat/paediatric-surgery', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/neuro-surgery', destination: '/doctor/near-me/treat/neurology/brain-tumor-surgery-guide', permanent: true },
      { source: '/doctor/near-me/treat/surgical-oncology', destination: '/doctor/near-me/treat/oncology/surgical-oncology-center', permanent: true },
      { source: '/doctor/near-me/treat/administration', destination: '/doctors', permanent: true },
      { source: '/doctor/near-me/vellore/paediatrics', destination: '/doctor/near-me/vellore', permanent: true },
      { source: '/doctor/near-me/treat/neurology/stroke-recovery-exercises', destination: '/doctor/near-me/treat/neurology/stroke-unit-rehabilitation', permanent: true },
      { source: '/doctor/near-me/treat/acl-injuries', destination: '/doctor/near-me/treat/orthopaedics/acl-reconstruction-recovery', permanent: true },
      { source: '/doctor/near-me/treat/arthritis', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/concussion', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/elbow-pain', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/foot-and-ankle-pain', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/hand-and-wrist-pain', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/hip-pain', destination: '/doctor/near-me/treat/orthopaedics/hip-replacement-surgery-guide', permanent: true },
      { source: '/doctor/near-me/treat/knee-pain', destination: '/doctor/near-me/treat/orthopaedics/knee-replacement', permanent: true },
      { source: '/doctor/near-me/treat/lupus', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/osteoporosis', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/pain-management', destination: '/doctor/near-me/treat/oncology/cancer-pain-management', permanent: true },
      { source: '/doctor/near-me/treat/pediatric-orthopaedics', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/running-injuries', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/scoliosis', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/sarcoma', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/shoulder-pain', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/sports-health', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/sports-injuries', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/vasculitis', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/aneurysm', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/back-pain', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/brain-tumors', destination: '/doctor/near-me/treat/neurology/brain-tumor-surgery-guide', permanent: true },
      { source: '/doctor/near-me/treat/brain-health', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/epilepsy', destination: '/doctor/near-me/treat/neurology/epilepsy-and-seizure-care', permanent: true },
      { source: '/doctor/near-me/treat/gamma-knife', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/multiple-sclerosis', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/movement-disorders', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/sleep', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/bladder-cancer', destination: '/doctor/near-me/treat/urology/bladder-cancer-diagnosis-treatment', permanent: true },
      { source: '/doctor/near-me/treat/stroke', destination: '/doctor/near-me/treat/neurology/stroke-management', permanent: true },
      { source: '/doctor/near-me/treat/breast-cancer', destination: '/doctor/near-me/treat/oncology/breast-cancer-screening-guide', permanent: true },
      { source: '/doctor/near-me/treat/colon-cancer', destination: '/doctor/near-me/treat/oncology/colon-cancer-treatment', permanent: true },
      { source: '/doctor/near-me/treat/cervical-cancer', destination: '/doctor/near-me/treat/obstetrics-gynaecology/cervical-cancer-screening', permanent: true },
      { source: '/doctor/near-me/treat/gynecological-cancer', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/head-and-neck-cancers', destination: '/doctor/near-me/treat/oncology/head-and-neck-cancer-care', permanent: true },
      { source: '/doctor/near-me/treat/kidney-cancer', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/leukemia', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/liver-cancer', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/lung-cancer', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/lymphoma', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/mesothelioma', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/melanoma', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/oral-cancer', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/nasal-cancer', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/ovarian-cancer', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/pancreatic-cancer', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/prostate-cancer', destination: '/doctor/near-me/treat/urology/prostate-surgery', permanent: true },
      { source: '/doctor/near-me/treat/testicular-cancer', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/throat-cancer', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/uterine-cancer', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/rare-cancers-and-blood-diseases', destination: '/doctor/near-me/treat/directory', permanent: true },
      { source: '/doctor/near-me/treat/blood-and-marrow-transplant', destination: '/doctor/near-me/treat/orthopaedics/bone-marrow-transplant-prep', permanent: true },
      { source: '/hospital-gallary', destination: '/gallery', permanent: true },
      { source: '/doctor/near-me/treat/general-surgery/laser-piles-treatment', destination: '/doctor/near-me/treat/proctology/laser-piles-treatment', permanent: true },
      { source: '/doctor/near-me/treat/general-surgery/laparoscopic-hysterectomy-guide', destination: '/doctor/near-me/treat/obstetrics-gynaecology/laparoscopic-hysterectomy-guide', permanent: true },
      
      // Additional departments & legacy mappings
      { source: '/departments/advanced-airway-management', destination: '/doctor/near-me/treat/critical-care-emergency-medicine', permanent: true },
      { source: '/departments/advanced-laparoscopic-urology', destination: '/doctor/near-me/treat/urology/kidney-stones', permanent: true },
      { source: '/departments/critical-care-medicine', destination: '/doctor/near-me/treat/critical-care-emergency-medicine', permanent: true },
      { source: '/departments/disaster-medicine', destination: '/doctor/near-me/treat/critical-care-emergency-medicine', permanent: true },
      { source: '/departments/endourology', destination: '/doctor/near-me/treat/urology/kidney-stones', permanent: true },
      { source: '/departments/laser-kidney-stone-surgery-rirs', destination: '/doctor/near-me/treat/urology/laser-kidney-stone-surgery-rirs', permanent: true },
      { source: '/departments/polytrauma-management', destination: '/doctor/near-me/treat/critical-care-emergency-medicine', permanent: true },
      { source: '/departments/prostate-surgery-turp-laser', destination: '/doctor/near-me/treat/urology/prostate-surgery', permanent: true },
      { source: '/departments/resuscitation-acls', destination: '/doctor/near-me/treat/critical-care-emergency-medicine', permanent: true },
      { source: '/departments/trauma-surgical-emergencies', destination: '/doctor/near-me/treat/critical-care-emergency-medicine', permanent: true },
      { source: '/doctor/near-me/nephrology', destination: '/doctors', permanent: true },
      { source: '/doctor/near-me/oncology', destination: '/doctors', permanent: true },
      { source: '/services', destination: '/doctors', permanent: true },
      { source: '/scans', destination: '/diagnostics', permanent: true },
      { source: '/doctor/near-me/treat/gum-treatment/:path*', destination: '/doctor/near-me/treat/dentistry/gum-treatment', permanent: true },
      { source: '/doctor/near-me/treat/dentistry', destination: '/doctor/near-me/treat/dentistry/dentistry', permanent: true },
      // --- END AUDIT RECOVERY REDIRECTS ---
    ]
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
  typescript: {
    ignoreBuildErrors: true,
  },
  compiler: {
    removeConsole: process.env.NODE_ENV === 'production',
  },
  experimental: {
    optimizePackageImports: [
      'lucide-react',
      'healthicons-react',
      'framer-motion',
      '@heroui/react'
    ],
  },
};

export default nextConfig;
